---
- name: Copying .bash_profile file
  template:
    src: .bash_profile.j2
    dest: /home/{{ bash_username }}/.bashrc
  become_user: "{{ bash_username }}"

- name: Copying bash scripts to ~/bin
  copy:
    src: bin
    dest: /home/{{ bash_username }}
    mode: u+x,g+x,o+x
  become_user: "{{ bash_username }}"
